// Code generated by MockGen. DO NOT EDIT.
// Source: ../src/github.com/shashaneRanasinghe/simpleAPI/internal/repository/lecturerRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/shashaneRanasinghe/simpleAPI/internal/models"
)

// MockLecturerRepository is a mock of LecturerRepository interface.
type MockLecturerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLecturerRepositoryMockRecorder
}

// MockLecturerRepositoryMockRecorder is the mock recorder for MockLecturerRepository.
type MockLecturerRepositoryMockRecorder struct {
	mock *MockLecturerRepository
}

// NewMockLecturerRepository creates a new mock instance.
func NewMockLecturerRepository(ctrl *gomock.Controller) *MockLecturerRepository {
	mock := &MockLecturerRepository{ctrl: ctrl}
	mock.recorder = &MockLecturerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLecturerRepository) EXPECT() *MockLecturerRepositoryMockRecorder {
	return m.recorder
}

// CreateLecturer mocks base method.
func (m *MockLecturerRepository) CreateLecturer(lecturer *models.Lecturer) (*models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLecturer", lecturer)
	ret0, _ := ret[0].(*models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLecturer indicates an expected call of CreateLecturer.
func (mr *MockLecturerRepositoryMockRecorder) CreateLecturer(lecturer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLecturer", reflect.TypeOf((*MockLecturerRepository)(nil).CreateLecturer), lecturer)
}

// DeleteLecturer mocks base method.
func (m *MockLecturerRepository) DeleteLecturer(id int) (*models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLecturer", id)
	ret0, _ := ret[0].(*models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLecturer indicates an expected call of DeleteLecturer.
func (mr *MockLecturerRepositoryMockRecorder) DeleteLecturer(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLecturer", reflect.TypeOf((*MockLecturerRepository)(nil).DeleteLecturer), id)
}

// GetAllLecturers mocks base method.
func (m *MockLecturerRepository) GetAllLecturers() ([]models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLecturers")
	ret0, _ := ret[0].([]models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLecturers indicates an expected call of GetAllLecturers.
func (mr *MockLecturerRepositoryMockRecorder) GetAllLecturers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLecturers", reflect.TypeOf((*MockLecturerRepository)(nil).GetAllLecturers))
}

// GetLecturer mocks base method.
func (m *MockLecturerRepository) GetLecturer(id int) (*models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLecturer", id)
	ret0, _ := ret[0].(*models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLecturer indicates an expected call of GetLecturer.
func (mr *MockLecturerRepositoryMockRecorder) GetLecturer(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLecturer", reflect.TypeOf((*MockLecturerRepository)(nil).GetLecturer), id)
}

// SearchLecturer mocks base method.
func (m *MockLecturerRepository) SearchLecturer(searchString string, pagination models.Pagination, sortBy models.SortBy) (*models.LecturerSearchData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchLecturer", searchString, pagination, sortBy)
	ret0, _ := ret[0].(*models.LecturerSearchData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchLecturer indicates an expected call of SearchLecturer.
func (mr *MockLecturerRepositoryMockRecorder) SearchLecturer(searchString, pagination, sortBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchLecturer", reflect.TypeOf((*MockLecturerRepository)(nil).SearchLecturer), searchString, pagination, sortBy)
}

// UpdateLecturer mocks base method.
func (m *MockLecturerRepository) UpdateLecturer(lecturer *models.Lecturer) (*models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLecturer", lecturer)
	ret0, _ := ret[0].(*models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLecturer indicates an expected call of UpdateLecturer.
func (mr *MockLecturerRepositoryMockRecorder) UpdateLecturer(lecturer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLecturer", reflect.TypeOf((*MockLecturerRepository)(nil).UpdateLecturer), lecturer)
}
