// Code generated by MockGen. DO NOT EDIT.
// Source: ../src/github.com/shashaneRanasinghe/simpleAPI/internal/usecases/lecturer/lecturerUsecase.go

// Package mock_lecturer is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/shashaneRanasinghe/simpleAPI/internal/models"
)

// MockLecturerUsecase is a mock of LecturerUsecase interface.
type MockLecturerUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLecturerUsecaseMockRecorder
}

// MockLecturerUsecaseMockRecorder is the mock recorder for MockLecturerUsecase.
type MockLecturerUsecaseMockRecorder struct {
	mock *MockLecturerUsecase
}

// NewMockLecturerUsecase creates a new mock instance.
func NewMockLecturerUsecase(ctrl *gomock.Controller) *MockLecturerUsecase {
	mock := &MockLecturerUsecase{ctrl: ctrl}
	mock.recorder = &MockLecturerUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLecturerUsecase) EXPECT() *MockLecturerUsecaseMockRecorder {
	return m.recorder
}

// CreateLecturer mocks base method.
func (m *MockLecturerUsecase) CreateLecturer(student *models.Lecturer) (*models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLecturer", student)
	ret0, _ := ret[0].(*models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLecturer indicates an expected call of CreateLecturer.
func (mr *MockLecturerUsecaseMockRecorder) CreateLecturer(student interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLecturer", reflect.TypeOf((*MockLecturerUsecase)(nil).CreateLecturer), student)
}

// DeleteLecturer mocks base method.
func (m *MockLecturerUsecase) DeleteLecturer(id int) (*models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLecturer", id)
	ret0, _ := ret[0].(*models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLecturer indicates an expected call of DeleteLecturer.
func (mr *MockLecturerUsecaseMockRecorder) DeleteLecturer(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLecturer", reflect.TypeOf((*MockLecturerUsecase)(nil).DeleteLecturer), id)
}

// GetAllLecturers mocks base method.
func (m *MockLecturerUsecase) GetAllLecturers() ([]models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLecturers")
	ret0, _ := ret[0].([]models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLecturers indicates an expected call of GetAllLecturers.
func (mr *MockLecturerUsecaseMockRecorder) GetAllLecturers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLecturers", reflect.TypeOf((*MockLecturerUsecase)(nil).GetAllLecturers))
}

// GetLecturer mocks base method.
func (m *MockLecturerUsecase) GetLecturer(id int) (*models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLecturer", id)
	ret0, _ := ret[0].(*models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLecturer indicates an expected call of GetLecturer.
func (mr *MockLecturerUsecaseMockRecorder) GetLecturer(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLecturer", reflect.TypeOf((*MockLecturerUsecase)(nil).GetLecturer), id)
}

// SearchLecturer mocks base method.
func (m *MockLecturerUsecase) SearchLecturer(searchString string, pagination models.Pagination, sortBy models.SortBy) (*models.LecturerSearchData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchLecturer", searchString, pagination, sortBy)
	ret0, _ := ret[0].(*models.LecturerSearchData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchLecturer indicates an expected call of SearchLecturer.
func (mr *MockLecturerUsecaseMockRecorder) SearchLecturer(searchString, pagination, sortBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchLecturer", reflect.TypeOf((*MockLecturerUsecase)(nil).SearchLecturer), searchString, pagination, sortBy)
}

// UpdateLecturer mocks base method.
func (m *MockLecturerUsecase) UpdateLecturer(student *models.Lecturer) (*models.Lecturer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLecturer", student)
	ret0, _ := ret[0].(*models.Lecturer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLecturer indicates an expected call of UpdateLecturer.
func (mr *MockLecturerUsecaseMockRecorder) UpdateLecturer(student interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLecturer", reflect.TypeOf((*MockLecturerUsecase)(nil).UpdateLecturer), student)
}
