// Code generated by MockGen. DO NOT EDIT.
// Source: ../src/github.com/shashaneRanasinghe/simpleAPI/internal/repository/studentRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/shashaneRanasinghe/simpleAPI/internal/models"
)

// MockStudentRepository is a mock of StudentRepository interface.
type MockStudentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudentRepositoryMockRecorder
}

// MockStudentRepositoryMockRecorder is the mock recorder for MockStudentRepository.
type MockStudentRepositoryMockRecorder struct {
	mock *MockStudentRepository
}

// NewMockStudentRepository creates a new mock instance.
func NewMockStudentRepository(ctrl *gomock.Controller) *MockStudentRepository {
	mock := &MockStudentRepository{ctrl: ctrl}
	mock.recorder = &MockStudentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentRepository) EXPECT() *MockStudentRepositoryMockRecorder {
	return m.recorder
}

// CreateStudent mocks base method.
func (m *MockStudentRepository) CreateStudent(student *models.Student) (*models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudent", student)
	ret0, _ := ret[0].(*models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStudent indicates an expected call of CreateStudent.
func (mr *MockStudentRepositoryMockRecorder) CreateStudent(student interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudent", reflect.TypeOf((*MockStudentRepository)(nil).CreateStudent), student)
}

// DeleteStudent mocks base method.
func (m *MockStudentRepository) DeleteStudent(id int) (*models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudent", id)
	ret0, _ := ret[0].(*models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStudent indicates an expected call of DeleteStudent.
func (mr *MockStudentRepositoryMockRecorder) DeleteStudent(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudent", reflect.TypeOf((*MockStudentRepository)(nil).DeleteStudent), id)
}

// GetAllStudents mocks base method.
func (m *MockStudentRepository) GetAllStudents() ([]models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStudents")
	ret0, _ := ret[0].([]models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStudents indicates an expected call of GetAllStudents.
func (mr *MockStudentRepositoryMockRecorder) GetAllStudents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStudents", reflect.TypeOf((*MockStudentRepository)(nil).GetAllStudents))
}

// GetStudent mocks base method.
func (m *MockStudentRepository) GetStudent(id int) (*models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudent", id)
	ret0, _ := ret[0].(*models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudent indicates an expected call of GetStudent.
func (mr *MockStudentRepositoryMockRecorder) GetStudent(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudent", reflect.TypeOf((*MockStudentRepository)(nil).GetStudent), id)
}

// SearchStudent mocks base method.
func (m *MockStudentRepository) SearchStudent(searchString string, pagination models.Pagination, sortBy models.SortBy) (*models.StudentSearchData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchStudent", searchString, pagination, sortBy)
	ret0, _ := ret[0].(*models.StudentSearchData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchStudent indicates an expected call of SearchStudent.
func (mr *MockStudentRepositoryMockRecorder) SearchStudent(searchString, pagination, sortBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchStudent", reflect.TypeOf((*MockStudentRepository)(nil).SearchStudent), searchString, pagination, sortBy)
}

// UpdateStudent mocks base method.
func (m *MockStudentRepository) UpdateStudent(student *models.Student) (*models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudent", student)
	ret0, _ := ret[0].(*models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStudent indicates an expected call of UpdateStudent.
func (mr *MockStudentRepositoryMockRecorder) UpdateStudent(student interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudent", reflect.TypeOf((*MockStudentRepository)(nil).UpdateStudent), student)
}
